export const EXPORT_HOUSEHOLD_TABLES = [
  "pets",
  "weight_records",
  "health_records",
  "vaccine_doses",
  "neonatal_records",
  "expenses",
  "reminders",
  "documents",
  "attachments",
  "document_attachments",
  "memories",
  "memory_pets",
  "memory_media",
  "products",
  "purchases",
  "product_reviews",
  "health_plans",
  "health_plan_templates",
  "health_plan_guides",
  "benefit_memberships",
] as const;
